{"name": "test_authentication_correct_credentials", "status": "skipped", "statusDetails": {"message": "Skipped: Skipping test due to unexpected login error: WebDriverException", "trace": "('C:\\\\Users\\\\usmaan.arshad\\\\PycharmProjects\\\\PythonProject\\\\tests\\\\Authentication\\\\test_authentication_correct_credential.py', 52, 'Skipped: Skipping test due to unexpected login error: WebDriverException')"}, "start": 1745400191221, "stop": 1745400259709, "uuid": "cd1802c1-0172-47f7-bcbe-c8806e23acec", "historyId": "7c5fdceb8be141e9360699da869202bf", "testCaseId": "7c5fdceb8be141e9360699da869202bf", "fullName": "tests.Authentication.test_authentication_correct_credential#test_authentication_correct_credentials", "labels": [{"name": "feature", "value": "Authentication - Correct Credentials"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "Validate successful authentication with correct credentials for the Heroku."}, {"name": "tag", "value": "test_demo"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests.Authentication"}, {"name": "suite", "value": "test_authentication_correct_credential"}, {"name": "host", "value": "RT-LT-597"}, {"name": "thread", "value": "14436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Authentication.test_authentication_correct_credential"}]}